fhdsl/DaSEH

config.yml, logistics.Rmd
- Correct dates
- Add information about the in person course to logistics
=> Add in person deets

config.yml, index.Rmd
Want to keep the fall dates open while making it clear that things are closed for summer :)
=> Updating some date language

README.md
I realized the readme.md still pointed to the JHU Intro to R page and also had the wrong course title. This PR corrects those issues.
=> Update readme so that it points to daseh.org

modules/Data_Summarization/Data_Summarization.Rmd, modules/Esquisse_Data_Visualization/Esquisse_Data_Visualization.Rmd, modules/Intro/Intro.Rmd, modules/Statistics/Statistics.Rmd, modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd
This PR contains fixes to small formatting issues as I find them in the DaSEH lectures.
=> Fixing format issues with lectures

.github/workflows/render-all-manual.yml, scripts/render_cheatsheets.R, scripts/render_resources.R
Update the workflow for all files
=> Get all the files!!!

scripts/render_html_list.R
Something happening that is making this work not as expected..
=> Clean up list of pdfs

config.yml, modules/Intro/Intro.Rmd, modules/Statistics/Statistics.Rmd, resources/dictionary.txt, resources/ignore-urls.txt
- Update Slack url
- Add research survey
=> Last minute updates to the Intro 😄 

modules/Basic_R/lab/Basic_R_Lab_Key.Rmd
folks in the JHU course struggled when an object was reused from the previous day (understandably)
=> Make Basic R carryover easier - no saved objects

modules/RStudio/RStudio.Rmd, modules/RStudio/lab/RStudio_Lab_Key.Rmd
- Update lab
- Remove slide about OH
=> Rstudio update

modules/Data_Input/Data_Input.Rmd, modules/Data_Input/lab/Data_Input_Lab_Key.Rmd, resources/R_Projects.Rmd
- update lab and lecture to correspond to overhaul last time in jHU course.
=> Input update

modules/Reproducibility/lab/Reproducibility_Lab.Rmd, modules/Reproducibility/lab/Reproducibility_Lab_Key.Rmd
explaining the set.seed part a bit more
=> making the lab a tad  more clear hopefully

modules/Data_Classes/lab/Data_Classes_Lab.Rmd, modules/Data_Classes/lab/Data_Classes_Lab_Key.Rmd, modules/Data_Cleaning/lab/Data_Cleaning_Lab.Rmd, modules/Data_Cleaning/lab/Data_Cleaning_Lab_Key.Rmd
Noticed a few typos that I'm fixing. Also added explanations of what a variable refers to before students work with it.
=> Fixing labs for data classes and data cleaning

modules/Data_Cleaning/Data_Cleaning.Rmd, modules/Data_Cleaning/lab/Data_Cleaning_Lab.Rmd
- updating the mint/ginger data to be about microplastics in the lecture
=> Cleaning stuff

modules/Data_Visualization/Data_Visualization.Rmd
- making it so the contents fit a tad more on the slides
=> Data viz updates

modules/Data_Visualization/Data_Visualization.Rmd
Could revert this, but since we are running behind.. wanted to shorten it at least this time.
=> Trim content for Data Viz

modules/Functions/lab/Functions_Lab.Rmd, modules/Functions/lab/Functions_Lab_Key.Rmd, modules/Functions/lab/Functions_Lab_Key.html
Realized there was a mistake in one of the questions for part two - this PR corrects it
=> change question in function lab

modules/Data_Cleaning/lab/Data_Cleaning_Lab.Rmd, modules/Data_Cleaning/lab/Data_Cleaning_Lab_Key.Rmd
For next time, not merging yet:
- changing out the word weight_loss for exposure, tried to do this with a previous [PR.](https://github.com/fhdsl/DaSEH/pull/91/commits/5d40f44035a6b7139e57c07ecb7c6bdade892cee).. confused
- I get that the last PR missed it for the Key ...which I just forgot to push... but the lab rmd was in that pr... hmm
=> changing weightloss to exposure again

index.Rmd, logistics.Rmd, materials_schedule.Rmd
Doing some small updates to make the times and dates more clear.
Resolves #85
=> Update dates and logistics to make time more clear

modules/Functions/lab/Functions_Lab.Rmd, modules/Functions/lab/Functions_Lab_Key.Rmd
Trying to address #121 
Switch the x and y labels and also tried to fix the description but I'm not 100% sure what needs to be added based on the issue and I wasn't there.
=> Update the functions lab

modules/Manipulating_Data_in_R/Manipulating_Data_in_R.Rmd, modules/Manipulating_Data_in_R/lab/Manipulating_Data_in_R_Lab.Rmd, modules/Manipulating_Data_in_R/lab/Manipulating_Data_in_R_Lab_Key.Rmd
Attempting to address #100 
I did not address the quotations in tidyverse thing though. It was unclear to me which parts were the biggest sticking points and how you'd like to address it. Let me know and I'm happy to add.
=> Addressing manipulating data buggies

modules/Intro/Intro.Rmd
=> Noticed broken link

modules/HW/homework2.Rmd
meant to do more of a fix https://github.com/fhdsl/DaSEH/pull/125/files
Previously I only fixed the key and not the homework directions
=> adding another fix to homework two

config.yml
made a new folder and copied and updated the old doc for this version of the code-a-thon
https://docs.google.com/document/d/1ZD-w0vc3Vtv1vf95h6323zaaxORg9vC7Hp4I_IUeW0I/edit?usp=sharing
=> Update config.yml for code-a-thon schedule doc

modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd
Fixing to show `clean_names` output - needed more slides to do so
Adding html file cause of some merging nonsense :P
=> [subsetting slide] output was not showing

resources.Rmd
some small changes to resources just added
=> resource page

modules/Reproducibility/Reproducibility.Rmd
adding a couple of gut checks before lab for #184
adding cheatsheet for #179  a posit sheet doesn't really make sense this time though
=> add gut check reproducibility

modules/Data_Cleaning/lab/Data_Cleaning_Lab_Key.Rmd
Addresses remaining issues from #93 
Added variable information to the first part of the lab, removed excess packages, and verified that `exposure` replaced `weight_loss`
=> [Data cleaning] fixing identified issues in lab

data/microplastics_in_blood.csv, modules/Data_Cleaning/Data_Cleaning.Rmd
we referred to pescatarian and vegetarian diets as diets - changing to foods to avoid stress for students around the word diet
=> [Cleaning] change data

modules/Manipulating_Data_in_R/Manipulating_Data_in_R.Rmd, modules/Manipulating_Data_in_R/lab/Manipulating_Data_in_R_Lab_Key.Rmd
Resolves #160 
Addresses part of #151 
Addresses part of #179 
Addresses part of #184
=> [Manipulating Data] Last minute updates..

modules/Data_Visualization/Data_Visualization.Rmd, modules/Factors/Factors.Rmd
- removing `dasehr` from lecture #151 
- adding Posit cheatsheet for #179
- adding Gut Checks for #184
- resolves #108
=> [Data viz and factors] updates

modules/Data_Visualization/Data_Visualization.Rmd
resolves #223 
and makes a better patchwork plot
=> Update data viz lecture

modules/Data_Visualization/lab/Data_Visualization_Lab_Key.Rmd
=> Update data viz Lab

index.Rmd, modules/Data_Input/Data_Input.Rmd, modules/Data_Input/lab/Data_Input_Lab_Key.Rmd
=> [Input] Why Projects; Small clarifying changes

modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd, modules/Subsetting_Data_in_R/lab/Subsetting_Data_in_R_Lab_Key.Rmd
=> Updating subsetting

modules/Data_Visualization/lab/Data_Visualization_Lab_Key.Rmd
=> fix a typo

modules/Data_Cleaning/lab/Data_Cleaning_Lab_Key.Rmd
Resolves #210 
This PR adds a sentence at the beginning to tell students to assign dataset to an object called "ces". This was done in the code, but the instructions did not explicitly tell students to use this object name.
=> [Data Cleaning] lab updates_Dec2024

modules/Data_Cleaning/Data_Cleaning.Rmd
Resolves #211 
Slide 65 had a missing carat in the code (line 735 in the Rmd)
=> [Data Cleaning] update lecture Jan2025

data/microplastics_in_blood.csv, modules/Data_Cleaning/Data_Cleaning.Rmd
resolves #266 
resolves #216 
Updating case_when examples (.default) - adding more slides and simplifying recoding
=> Cleaning improvement

resources.Rmd, resources/cleaning_names.Rmd
Resolves #263 
https://github.com/jhudsl/intro_to_r/pull/651/files
=> Add resources from JHU Course

resources.Rmd
updating resources to match intro to R
=> adding stringr cheatsheet

modules/Reproducibility/Reproducibility.Rmd
resolves #195 - fixing cheatsheet mentions to be consistent
=> tiny edits to resources on reproducibility content

.github/workflows/pull_request.yml, .github/workflows/render-site.yml
Bumping up version to decrease risk related to this security problem: https://thehackernews.com/2025/03/github-action-compromise-puts-cicd.html
=> Updating tj-actions/changed-files

modules/Intro/Intro.Rmd
=> Add info about AI for programming

DaSEH.Rproj, modules/Data_Summarization/Data_Summarization.Rmd
=> Summarization updates

modules/Data_Cleaning/Data_Cleaning.Rmd, modules/Manipulating_Data_in_R/lab/Manipulating_Data_in_R_Lab_Key.Rmd
=> Manipulation updates and resolve a pipe related bug

resources.Rmd, resources/ocs_practice.Rmd
- making new ocs_practice page
- adding jhu link and this page on the resource page in an OCS section on the resource page and moving OCS mention out of it's current location
- resolves #142
=> adding OCS recommendations

modules/Data_Cleaning/Data_Cleaning.Rmd, modules/Setup/Setup.Rmd
This addresses part of issue #306
=> Correct typo
